Erp\Bundle\ObjectValueBundle\Entity\Citizen:
  type: entity
  #repositoryClass: Erp\Bundle\ObjectValueBundle\Infrastructure\ORM\Repository\CitizenRepository
  table: objectvalue_citizen
  inheritanceType: JOINED
  fields:
    initname:
      type: string
      length: 64
      nullable: true
    firstname:
      type: string
      length: 256
      nullable: false
    lastname:
      type: string
      length: 256
      nullable: true
    birthDate:
      type: date_immutable
      nullable: true
    religious:
      type: string
      length: 64
      nullable: true
    issueDate:
      type: date_immutable
      nullable: true
    expiredDate:
      type: date_immutable
      nullable: true
