Erp\Bundle\ObjectValueBundle\Entity\Corporate:
  type: entity
  #repositoryClass: Erp\Bundle\ObjectValueBundle\Infrastructure\ORM\Repository\CorporateRepository
  table: objectvalue_corporate
  inheritanceType: JOINED
  fields:
    registrationDate:
      type: date_immutable
      nullable: true
    category:
      type: string
      length: 128
      nullable: true
    corporateName:
      type: string
      length: 256
      nullable: true
    main:
      type: boolean
      nullable: false
    branch:
      type: string
      length: 256
      nullable: true
